### ISSUE TITLE
Whats the point of this?

### ISSUE THREAD

**Issue by TypicalModMaker** [ComuGamersES/qubo-blocker#1]
Whats the point of blocking motd packet at your backend server when iptables exist?:

If you block the list packet on your bungeecord no one will be able to see the motd

This plugin doesn't make any sense.

**Comment by Pabszito** [comment]
This is not blocking the server list packet of your BungeeCord proxy, it is blocking the one from its backend servers (Bukkit). If you mean it is also being blocked for the proxy, there’s a whitelist option for that as well.

There are many people that for some reason do Minecraft networks in shared hostings, which probably don’t allow a firewall at all. Since server list packets would be blocked by using this, your server wouldn’t be visible to tools using them. It will be visible through nmap, though.

There’s actually a disclaimer about firewalls in [this wiki](https://github.com/ComuGamersES/sentey/wiki) (similar plugin), I just didn’t even bother to make one for this plugin since it was mostly rushed and made as a joke in around 10 minutes.
